on:
  push:
    branches: [ "master" ]
jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: macos-latest
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a
      - name: Checkout repo from branch
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install npm dependency
        run: npm install
      - name: Cache cocoapods
        uses: actions/cache@v3
        with:
          path: /ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install bundler
        run: |
          cd ios
          gem install bundler
      - name: Install gem plugins
        run: |
            cd ios
            bundle install
      - name: Install pod dependency
        run: |
          cd ios
          bundle exec pod install
      - name: Build iOS JS Bundle
        run: |
          npx react-native run-ios --configuration Release
      - name: Find Build Artifact
        id: find-build
        run: |
          APP_PATH=$(find $RUNNER_TEMP -name "GuruChatApp.app" | head -n 1)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-build-artifact
          path: ${{ env.APP_PATH }}
          retention-days: 30