on:
  push:
    branches: [ "master" ]
jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: macos-latest
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a
      - name: Checkout repo from branch
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install npm dependency
        run: npm install
      - name: Cache cocoapods
        uses: actions/cache@v3
        with:
          path: /ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install bundler
        run: |
          cd ios
          gem install bundler
      - name: Install gem plugins
        run: |
            cd ios
            bundle install
      - name: Install pod dependency
        run: |
          cd ios
          bundle exec pod install
      - name: Build iOS JS Bundle
        run: |
          npx react-native run-ios --configuration Release
  android-build:
    name: Android Dev Build
    runs-on: ubuntu-latest
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a
      - name: Checkout repo from dev branch
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install npm dependency
        run: npm install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew build
      - name: Build Android JS Bundle
        run: |
          yarn run package-android
