on:
  push:
    branches: [ "master" ]
jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: macos-latest
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a
      - name: Checkout repo from branch
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install npm dependency
        run: npm install
      - name: Cache cocoapods
        uses: actions/cache@v3
        with:
          path: /ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install bundler
        run: |
          cd ios
          gem install bundler
      - name: Install gem plugins
        run: |
            cd ios
            bundle install
      - name: Install pod dependency
        run: |
          cd ios
          bundle exec pod install
      - name: Build iOS JS Bundle
        run: |
          npx react-native run-ios --configuration Release
      - name: Preliminary Find for Build Artifact
        id: preliminary-find
        run: |
          echo "Searching for GuruChatApp.app in common directories..."
          find ~/Library/Developer/Xcode/DerivedData -name "GuruChatApp.app" -print -quit
      - name: Find Build Artifact
        id: find-build
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "GuruChatApp.app" -print -quit)
          if [[ -z "$APP_PATH" ]]; then
            echo "GuruChatApp.app not found"
            exit 1
          fi
          echo "Found APP_PATH: $APP_PATH"
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-build-artifact
          path: ${{ env.APP_PATH }}
          retention-days: 30